version: "3"

services:
  workspace:
    container_name: php
    # ./workspace/Dockerfile でイメージをビルド
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "443:443"
    volumes:
      - "../:/var/www/"

  # MySQL
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: mlc
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  # phpMyAdmin
  phpMyAdmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: root
